@startuml Тёплый дом

entity "Клиент" as Client {
  id: UUID
  --
  surname: string
  name: string
  patronymic: string
  login: string
  phone: string
  password: hashed_string
  created_at: datetime
}

entity "Дом" as House {
  id: UUID
  --
  address: string
  owner_uuid: UUID
  active: bool
}

entity "Устройство" as Device {
  id: UUID
  --
  type: enum
  active: bool
  seria: string
  active: bool
  house_uuid: UUID
  active_conf_uuid: UUID
}

entity "Конфигурация устройства" as DeviceConfig {
  id: UUID
  --
  conf: json
  device_uuid: UUID
}

Client }--o{ House : "У дома может быть несколько пользователей. А один из них владелец. Пользователь может управлять несколькими домами\nУ клиента не обязательно имеется дом, возможно будет позже, пока просто появился в системе, но не подключил свой дом (или не присоединился к существующему)"
House --o{ Device : "К дому можно подключить несколько устройств"
Device --{ DeviceConfig : "Устройство может иметь несколько конфигураций, между которыми можно переключаться"

@enduml